version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: campusapp_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: campusapp
      POSTGRES_PASSWORD: campusapp_dev
      POSTGRES_DB: campusapp
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/db/migrations:/docker-entrypoint-initdb.d

volumes:
  pgdata:
